#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

set -o errexit

echo "Running Pre-Commit Git hooks"

cd ./server

echo "Running tests"
php vendor/bin/phpunit tests/

echo "Running phpcs"
php vendor/bin/phpcs --standard=ruleset.xml app/

echo "Running self-diagnosis"
php artisan self-diagnosis
